const index = require('../routes/index')
const auth = require('../routes/auth')
const home = require('../routes/home')
const lecture = require('../routes/lecture')
const presentation = require('../routes/presentation')
const partials = require('../routes/partials')

const ws = {}
ws.answer = require('../routes/ws/answer')
ws.instruction = require('../routes/ws/instruction')
ws.material = require('../routes/ws/material')
ws.presentation = require('../routes/ws/presentation')
ws.question = require('../routes/ws/question')
ws.date = require('../routes/ws/date')
ws.works = require('../routes/ws/works')
ws.event = require('../routes/ws/event')
ws.submissions = require('../routes/ws/submissions')
ws.lecture = require('../routes/ws/lecture')
ws.person = require('../routes/ws/person')

module.exports = function routesConfig(app) {
  app.use('/', index)
  app.use('/', auth)
  app.use('/', home)
  app.use('/', lecture)
  app.use('/', presentation)
  app.use('/', partials)

  app.use('/api', ws.answer)
  app.use('/api', ws.instruction)
  app.use('/api', ws.material)
  app.use('/api', ws.presentation)
  app.use('/api', ws.question)
  app.use('/api', ws.date)
  app.use('/api', ws.works)
  app.use('/api', ws.event)
  app.use('/api', ws.submissions)
  app.use('/api', ws.lecture)
  app.use('/api', ws.person)
}
